
server:
  port: 8081
  servlet:
    context-path: /userportal
spring:
  dataSource: 
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp